config/routes.rb
Rails.application.routes.draw do
  resources :diagnoses
  root to:    'home#index'
  get         'home/index'
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diagnosis.rb
class Diagnosis < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
  validates :communication, presence: true
  validates :planning, presence: true
  validates :dexterous, presence: true
  validates :tidy, presence: true
  validates :physically, presence: true
  validates :muscle, presence: true
  validates :intelligence, presence: true
  validates :careful, presence: true
  validates :pride, presence: true
  validates :picky, presence: true
  validates :destruction, presence: true
  validates :narrow, presence: true
  validates :dirt, presence: true
  validates :high, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :diagnoses

  validates :name, presence: true
  validates :password,        presence: true
  validates :email,           presence: true, uniqueness: true

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guest_user"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
  end

  def check_guest
    email = resource&.email || params[:user][:email].downcase
    if email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの変更・削除はできません。'
    end
  end

  before_action :set_current_user

  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end
end

app/controllers/diagnoses_controller.rb
class DiagnosesController < ApplicationController
  def index
  end

  def new
    @diagnosis = Diagnosis.new(user_id: current_user.id)
  end

  def show
    @diagnosis = current_user.diagnoses.find(params[:id])
    @craftsmanship = (@diagnosis.communication.to_i + @diagnosis.planning.to_i + @diagnosis.dexterous.to_i +
                      @diagnosis.tidy.to_i + @diagnosis.physically.to_i + @diagnosis.muscle.to_i + @diagnosis.intelligence.to_i +
                      @diagnosis.pride.to_i + @diagnosis.picky.to_i) * 2.4 - @diagnosis.destruction.to_i * 3 -
                      @diagnosis.narrow.to_i - @diagnosis.dirt.to_i - @diagnosis.high.to_i - @diagnosis.careful.to_i * 2
    gon.communication = @diagnosis.communication
    gon.planning = @diagnosis.planning
    gon.dexterous = @diagnosis.dexterous
    gon.tidy = @diagnosis.tidy
    gon.physically = @diagnosis.physically
    gon.muscle = @diagnosis.muscle
    gon.intelligence = @diagnosis.intelligence
    gon.careful = @diagnosis.careful
    gon.pride = @diagnosis.pride
    gon.picky = @diagnosis.picky
    gon.destruction = @diagnosis.destruction
    gon.narrow = @diagnosis.narrow
    gon.dirt = @diagnosis.dirt
    gon.high = @diagnosis.high
  end

  def create
    @diagnosis = Diagnosis.new(diagnosis_params)
    if @diagnosis.save
      flash[:notice] = "診断が完了しました"
      redirect_to diagnosis_path(@diagnosis.id)
    else
      flash[:notice] = "全ての項目をチェックしてください"
      redirect_to :action => "new"
    end
  end

  def diagnosis_params
    params.require(:diagnosis).permit(:id, :communication, :planning, :dexterous, :tidy, :physically, :muscle, :intelligence,
                                      :careful, :pride, :picky, :narrow, :dirt, :destruction, :high, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  before_action :check_guest, only: :create
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: [:update, :destroy]
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  BASE_TITLE = "CraftsMan".freeze

  def full_title(page_title)
    page_title.blank? ? BASE_TITLE : "#{page_title}-#{BASE_TITLE}"
  end
end

app/helpers/diagnoses_helper.rb
module DiagnosesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="top">
  <div class="top-main">
    <%= render 'shared/header' %>
    <div class="top-flame">
      <p>建築現場で働きたいあなたへ<br>あなたの職人度を診断します</p>
      <% if user_signed_in? %>
        <%= link_to new_diagnosis_path do %>
          <button class= "btn-link" >診断する</button>
        <% end %>
      <% else %>
        <%= link_to users_guest_sign_in_path, method: :post do %>
          <button class= "btn-link" >Guest Login</button>
        <% end %>
      <% end %>
    </div>
  </div>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Caveat" rel="stylesheet">
    <script src="https://kit.fontawesome.com/87de6304b2.js" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body id="body">
    <%= render 'shared/flash_messages' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <% if #{message_type} == notice %>
      <i class="fa-regular fa-circle-check i-check"></i>
    <% else %>
    <% end %>
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer-inner">
    <p>©︎2023 CRAFTSMAN</p>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="header-inner">
    <div class="header-left-nav">
      <%= link_to "CraftsMan", root_path, class: "mx-3 link title" %>
    </div>
    <div class="header-right-nav">
      <% if user_signed_in? %>
        <%= link_to destroy_user_session_path, method: :delete, class: "dropdown__item-link" do %>
          <button class= "btn-link" >ログアウト</button>
        <% end %>
      <% else %>
        <%= link_to new_user_session_path do %>
          <button class= "btn-link" >ログイン</button>
        <% end %>
        <%= link_to new_user_registration_path do %>
          <button class= "btn-link" >新規登録</button>
        <% end %>
      <% end %>
    </div>
  </div>
</header>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>